version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Singapore
  open-pull-requests-limit: 10
  reviewers:
  - iphoting
  assignees:
  - iphoting
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: coffeescript
    versions:
    - ">= 2.a, < 3"
