# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Install expect
      run: sudo apt-get install expect
    - name: Install Dependencies
      run: npm ci
    - name: Run Build
      run: npm run build --if-present
    - name: Run Tests
      env:
        HUBOT_S3_BRAIN_ACCESS_KEY_ID: ${{ secrets.HUBOT_S3_BRAIN_ACCESS_KEY_ID }}
        HUBOT_S3_BRAIN_SECRET_ACCESS_KEY: ${{ secrets.HUBOT_S3_BRAIN_SECRET_ACCESS_KEY }}
      run: npm test
